# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import parameter_server_pb2 as parameter__server__pb2


class ParameterServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/distributed_training.ParameterServer/RegisterWorker',
                request_serializer=parameter__server__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.RegisterWorkerResponse.FromString,
                )
        self.DistributeModelWeights = channel.stream_stream(
                '/distributed_training.ParameterServer/DistributeModelWeights',
                request_serializer=parameter__server__pb2.ModelWeightsRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.ModelWeightsResponse.FromString,
                )
        self.DistributeDataset = channel.unary_unary(
                '/distributed_training.ParameterServer/DistributeDataset',
                request_serializer=parameter__server__pb2.DatasetRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.DatasetResponse.FromString,
                )
        self.ReceiveGradients = channel.stream_unary(
                '/distributed_training.ParameterServer/ReceiveGradients',
                request_serializer=parameter__server__pb2.GradientsRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.GradientsResponse.FromString,
                )
        self.DistributeAveragedGradients = channel.unary_stream(
                '/distributed_training.ParameterServer/DistributeAveragedGradients',
                request_serializer=parameter__server__pb2.AveragedGradientsRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.AveragedGradientsResponse.FromString,
                )
        self.RequestNextDatasetPortion = channel.unary_unary(
                '/distributed_training.ParameterServer/RequestNextDatasetPortion',
                request_serializer=parameter__server__pb2.NextDatasetPortionRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.NextDatasetPortionResponse.FromString,
                )


class ParameterServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributeModelWeights(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributeDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveGradients(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributeAveragedGradients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestNextDatasetPortion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=parameter__server__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=parameter__server__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'DistributeModelWeights': grpc.stream_stream_rpc_method_handler(
                    servicer.DistributeModelWeights,
                    request_deserializer=parameter__server__pb2.ModelWeightsRequest.FromString,
                    response_serializer=parameter__server__pb2.ModelWeightsResponse.SerializeToString,
            ),
            'DistributeDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributeDataset,
                    request_deserializer=parameter__server__pb2.DatasetRequest.FromString,
                    response_serializer=parameter__server__pb2.DatasetResponse.SerializeToString,
            ),
            'ReceiveGradients': grpc.stream_unary_rpc_method_handler(
                    servicer.ReceiveGradients,
                    request_deserializer=parameter__server__pb2.GradientsRequest.FromString,
                    response_serializer=parameter__server__pb2.GradientsResponse.SerializeToString,
            ),
            'DistributeAveragedGradients': grpc.unary_stream_rpc_method_handler(
                    servicer.DistributeAveragedGradients,
                    request_deserializer=parameter__server__pb2.AveragedGradientsRequest.FromString,
                    response_serializer=parameter__server__pb2.AveragedGradientsResponse.SerializeToString,
            ),
            'RequestNextDatasetPortion': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestNextDatasetPortion,
                    request_deserializer=parameter__server__pb2.NextDatasetPortionRequest.FromString,
                    response_serializer=parameter__server__pb2.NextDatasetPortionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_training.ParameterServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParameterServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed_training.ParameterServer/RegisterWorker',
            parameter__server__pb2.RegisterWorkerRequest.SerializeToString,
            parameter__server__pb2.RegisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DistributeModelWeights(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/distributed_training.ParameterServer/DistributeModelWeights',
            parameter__server__pb2.ModelWeightsRequest.SerializeToString,
            parameter__server__pb2.ModelWeightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DistributeDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed_training.ParameterServer/DistributeDataset',
            parameter__server__pb2.DatasetRequest.SerializeToString,
            parameter__server__pb2.DatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveGradients(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/distributed_training.ParameterServer/ReceiveGradients',
            parameter__server__pb2.GradientsRequest.SerializeToString,
            parameter__server__pb2.GradientsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DistributeAveragedGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/distributed_training.ParameterServer/DistributeAveragedGradients',
            parameter__server__pb2.AveragedGradientsRequest.SerializeToString,
            parameter__server__pb2.AveragedGradientsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestNextDatasetPortion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed_training.ParameterServer/RequestNextDatasetPortion',
            parameter__server__pb2.NextDatasetPortionRequest.SerializeToString,
            parameter__server__pb2.NextDatasetPortionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
